### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by jeremie-olivier** [THP-Lab/intuition-recommendation-assistant#4]
The mockup links should be accessible from the assistant documentation of the docusaurus of THP lab

**Comment by ZealRa** [comment]
First Mockup link here https://design.penpot.app/#/workspace/345886aa-f4d1-8033-8005-60dda7b75c50/345886aa-f4d1-8033-8005-611289694228?page-id=401b0290-175c-80ee-8005-65ec2b62f303
